"""Initial migration

Revision ID: 157088439244
Revises: 
Create Date: 2025-10-06 14:49:45.747730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157088439244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('party_a', sa.String(length=255), nullable=False),
    sa.Column('party_b', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('obligation_id', sa.String(length=100), nullable=False),
    sa.Column('party', sa.String(length=255), nullable=False),
    sa.Column('obligation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('penalty_currency', sa.String(length=10), nullable=True),
    sa.Column('rebate_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rebate_currency', sa.String(length=10), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('trigger_conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('next_check', sa.DateTime(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_evidence', sa.Text(), nullable=True),
    sa.Column('breach_count', sa.Integer(), nullable=True),
    sa.Column('last_breach_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('obligation_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('evidence_data', sa.Text(), nullable=True),
    sa.Column('related_transactions', sa.Text(), nullable=True),
    sa.Column('compliance_data', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.Text(), nullable=True),
    sa.Column('notification_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('obligations')
    op.drop_table('contracts')
    # ### end Alembic commands ###
