"""Add linked entity fields to contracts and check fields to        
     obligations

Revision ID: 6d1b50f347ad
Revises: 77b4b196545a
Create Date: 2026-01-11 18:01:18.145061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d1b50f347ad'
down_revision: Union[str, None] = '77b4b196545a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('linked_entity_id', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('linked_entity_type', sa.String(length=100), nullable=True))
    op.add_column('obligations', sa.Column('check_type', sa.String(length=100), nullable=True))
    op.add_column('obligations', sa.Column('check_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'check_parameters')
    op.drop_column('obligations', 'check_type')
    op.drop_column('contracts', 'linked_entity_type')
    op.drop_column('contracts', 'linked_entity_id')
    # ### end Alembic commands ###
