"""Add linked entity fields to contracts and check fields to        
     obligations

Revision ID: 77b4b196545a
Revises: 03ed2383a72d
Create Date: 2026-01-11 17:51:10.688896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b4b196545a'
down_revision: Union[str, None] = '03ed2383a72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
